const contactsPageData = {
  "/contacts.html": {
    title: "Контакты",
    contactsHero: {
      breadcrumbs: [
        { title: "Главная", href: "/" },
        { title: "Контакты", isCurrent: true },
        { title: "Наши клиники", isGhost: true },
      ],
      title: "Наши клиники",
      map: {
        imageSrc: "/images/contacts/map-base.png",
        imageAlt: "Схема расположения клиник Факт",
      },
      clinics: [
        {
          id: "pyatigorsk",
          active: true,
          tabCity: "Пятигорск",
          tabStreet: "Московская 6/4",
          addressLabel: "Адрес клиники",
          addressLines: ["г. Пятигорск,", "ул. Московская, д. 6/4"],
          routeText: "Построить маршрут",
          routeHref: "#",
          worktime: "Ежедневно с 9:00 до 19:00",
          phone: "8 800 333-4603",
          phoneHref: "tel:88003334603",
          callbackText: "Обратный звонок",
          callbackHref: "#",
          mail: "mng@factmed.ru",
          mailHref: "mailto:mng@factmed.ru",
          mailActionText: "Написать письмо",
          mailActionHref: "mailto:mng@factmed.ru",
          whatsappHref: "#",
          telegramHref: "#",
        },
        {
          id: "krasnodar",
          active: false,
          tabCity: "Краснодар",
          tabStreet: "Красноармейский переулок 18",
          addressLabel: "Адрес клиники",
          addressLines: ["г. Краснодар,", "Красноармейский пер., д. 18"],
          routeText: "Построить маршрут",
          routeHref: "#",
          worktime: "Ежедневно с 9:00 до 19:00",
          phone: "8 800 333-4603",
          phoneHref: "tel:88003334603",
          callbackText: "Обратный звонок",
          callbackHref: "#",
          mail: "mng@factmed.ru",
          mailHref: "mailto:mng@factmed.ru",
          mailActionText: "Написать письмо",
          mailActionHref: "mailto:mng@factmed.ru",
          whatsappHref: "#",
          telegramHref: "#",
        },
      ],
    },
    contactsSocials: {
      title: "Социальные сети",
      lead: "Мы максимально открыты и подтверждаем экспертность в соц.сетях",
      items: [
        {
          name: "YouTube",
          href: "#",
          followers: "2 500 подписчиков",
          iconType: "youtube",
          iconSrc: "/images/contacts-socials/youtube.svg",
          iconAlt: "Иконка YouTube",
        },
        {
          name: "ВКонтакте",
          href: "#",
          followers: "2 500 подписчиков",
          iconType: "vk",
          iconSrc: "/images/contacts-socials/vk.svg",
          iconAlt: "Иконка ВКонтакте",
        },
        {
          name: "RuTube",
          href: "#",
          followers: "2 500 подписчиков",
          iconType: "rutube",
          iconSrc: "/images/contacts-socials/rutube.svg",
          iconAlt: "Иконка RuTube",
        },
        {
          name: "Telegram",
          href: "#",
          followers: "2 500 подписчиков",
          iconType: "telegram",
          iconSrc: "/images/contacts-socials/telegram.svg",
          iconAlt: "Иконка Telegram",
        },
      ],
    },
  },
};

export default contactsPageData;
