const defaultDescription =
  "Сложнейшие офтальмологические операции, сравнимые с ювелирной работой, теперь выполняются ...";

const sportDescription =
  "В минувшие выходные мы стали частью впечатляющего всероссийского забега «ЗОбег» ...";

const newsPageData = {
  "/news.html": {
    title: "Новости",
    newsPage: {
      title: "Новости",
      cards: [
        {
          href: "#",
          modClass: "news__card news__card--active",
          imageDesktop: "/images/doctor-detail/article-main.webp",
          imageAlt: "Хирургия катаракты и лечение пресбиопии",
          tag: "# статья от врача",
          title: "хирургия катаракты и лечение пресбиопии",
          description:
            "В глазной клинике «ФАКТ» применяется самый современный на сегодняшний день метод хирургии",
          showButton: true,
          buttonText: "читать",
        },
        {
          href: "#",
          modClass: "news__card",
          imageDesktop: "/images/blog-card/1.webp",
          imageAlt: "Высокоточные операции на глазах доступны в Пятигорске",
          tag: "# новости",
          title: "Высокоточные операции на глазах доступны в Пятигорске",
          description: defaultDescription,
          showButton: true,
          buttonText: "читать",
        },
        {
          href: "#",
          modClass: "news__card",
          imageDesktop: "/images/doctors/1.webp",
          imageAlt: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          tag: "# справочник",
          title: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          description: sportDescription,
          showButton: true,
          buttonText: "читать",
        },
        {
          href: "#",
          modClass: "news__card",
          imageDesktop: "/images/ratings/1.webp",
          imageAlt: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          tag: "# справочник",
          title: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          description: sportDescription,
          showButton: true,
          buttonText: "читать",
        },
        {
          href: "#",
          modClass: "news__card",
          imageDesktop: "/images/patients/1.webp",
          imageAlt: "Высокоточные операции на глазах доступны в Пятигорске",
          tag: "# новости",
          title: "Высокоточные операции на глазах доступны в Пятигорске",
          description: defaultDescription,
          showButton: true,
          buttonText: "читать",
        },
        {
          href: "#",
          modClass: "news__card",
          imageDesktop: "/images/doctors/2.webp",
          imageAlt: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          tag: "# справочник",
          title: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          description: sportDescription,
          showButton: true,
          buttonText: "читать",
        },
        {
          href: "#",
          modClass: "news__card",
          imageDesktop: "/images/ratings/2.webp",
          imageAlt: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          tag: "# справочник",
          title: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          description: sportDescription,
          showButton: true,
          buttonText: "читать",
        },
        {
          href: "#",
          modClass: "news__card",
          imageDesktop: "/images/patients/2.webp",
          imageAlt: "Высокоточные операции на глазах доступны в Пятигорске",
          tag: "# новости",
          title: "Высокоточные операции на глазах доступны в Пятигорске",
          description: defaultDescription,
          showButton: true,
          buttonText: "читать",
        },
        {
          href: "#",
          modClass: "news__card",
          imageDesktop: "/images/doctors/3.webp",
          imageAlt: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          tag: "# справочник",
          title: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          description: sportDescription,
          showButton: true,
          buttonText: "читать",
        },
        {
          href: "#",
          modClass: "news__card",
          imageDesktop: "/images/ratings/3.webp",
          imageAlt: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          tag: "# справочник",
          title: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          description: sportDescription,
          showButton: true,
          buttonText: "читать",
        },
        {
          href: "#",
          modClass: "news__card",
          imageDesktop: "/images/patients/3.webp",
          imageAlt: "Высокоточные операции на глазах доступны в Пятигорске",
          tag: "# новости",
          title: "Высокоточные операции на глазах доступны в Пятигорске",
          description: defaultDescription,
          showButton: true,
          buttonText: "читать",
        },
        {
          href: "#",
          modClass: "news__card",
          imageDesktop: "/images/doctors/4.webp",
          imageAlt: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          tag: "# справочник",
          title: "Глазная клиника «ФАКТ» — за здоровый образ жизни и спорт!",
          description: sportDescription,
          showButton: true,
          buttonText: "читать",
        },
      ],
    },
  },
};

export default newsPageData;
